# Nom de l'application
spring.application.name=projetfind-etude

# ---------- PostgreSQL configuration des bases de données  ----------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestion_utilisateurs}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------- Port HTTP ----------
server.port=${PORT:8080}

#----active l’affichage de petits détails dans les erreurs 500 côté API ---
app.errors.include-details=true

# Secret pour signer les JWT je doit m... une longue phrase
app.jwt.secret=TOUJOURS-mettre-une-tres-tres-longue-phrase-secrete-impossible-a-deviner-afin-de-crée-la-clé-sécrete-utilisée-pour-signer-les-tokens-jwt-ramah-soramtfr-projet-2025!!

# Durée (en minutes)
app.jwt.exp-minutes=120



